---
title: "Untitled"
author: "AS"
date: "September 7, 2017"
output:
  pdf_document: default
  html_document: default
---
 
## Setup

Load the following packages and load the data base access scipt:


```{r setup, echo=TRUE, message=FALSE}
## load packages
require(RPostgreSQL)
require(sf)
require(knitr)

## load access data
prjdir = '/home/andreas/Documents/Projects/pesticides-organisms'
source(file.path(prjdir, 'Rmd/R/amelung_access.R'))
```

## Loading data

Here you find the code necessary to query our PostgresSQL data base: bfg_monitoring

```{r load-MZB-data, echo=TRUE, message=FALSE}
drv = dbDriver("PostgreSQL")
con = dbConnect(drv, dbname = DBname, user = DBuser, host = DBhost, port = DBport, password = DBpassword)

dat = dbGetQuery(con, "SELECT *
                       FROM mzb.mzb_samples
                       WHERE site_id = 'NW_13067'
                       LIMIT 100")

dbDisconnect(con)
dbUnloadDriver(drv)
```

```{r load-PSM-data, echo=TRUE, message=FALSE}
drv = dbDriver("PostgreSQL")
con = dbConnect(drv, dbname = DBname, user = DBuser, host = DBhost, port = DBport, password = DBpassword)

psm_sites = dbGetQuery(con, "SELECT *
                             FROM views.psm_sites_2005")
psm_samples = dbGetQuery(con, "SELECT *
                               FROM views.psm_samples_2005 sam
                               JOIN phch.phch_variables var ON var.variable_id = sam.variable_id")

dbDisconnect(con)
dbUnloadDriver(drv)
```



## Plot a histogram of the measured variable

Ploting a histogram from the just queried data.

```{r histogram}
hist(log10(dat$ind_qm))
```

